### ISSUE TITLE
Google API Scope Required Now(?)

### ISSUE THREAD

**Issue by J3G3** [Daanoz/ha-google-photos#16]
At the final step of authenticating through Google I received this error pop-up

     "Failed to query google api: Request had insufficient authentication scopes."

FIXED by...
-- Add Scope to View for Photos API  ('sensitive' unfortunately)
-- Revert publishing status to "Testing"  (otherwise proceed through a verification process)
-- Add myself as a Test User

First time I've used Google's API's so, its very likely I missed something from your instructions.

Your instructions were great -- and this addon was exactly what I needed!!  Thank you
```

**Comment by Daanoz** [comment]
Yeah, it can be tricky to get right, I wish there was a better way to do this. It's crucial however to follow the steps to the letter, and to not do anything extra (like for example setting a logo) as that would require verification to be done.

I would recommend however to see where the issue is exactly, as have the publishing status to "testing" will mean that every 7 days you will need to login again with your google account... Also, after making changes, wait a couple of minutes, it sometimes takes a bit of time to be fully configured.

**Comment by Daanoz** [comment]
As a reference, I added some screenshots how it (should) look like:
**OAuth consent screen setup**
![OAuth consent screen setup](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsentOverview.png)
**OAuth consent screen edit, step1**
![OAuth consent screen edit, step1](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent1.png)
**OAuth consent screen edit, step2**
![OAuth consent screen edit, step2](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent2.png)
**OAuth consent screen edit, step3**
![OAuth consent screen edit, step3](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent3.png)
**OAuth consent screen edit, step4**
![OAuth consent screen edit, step4](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent4.png)
**Credentials**
![Credentials](https://github.com/Daanoz/ha-google-photos/raw/main/docs/Credentials.png)
