### ISSUE TITLE
Support offline usage, fetch and store entire album on disk

### ISSUE THREAD

**Issue by j9brown** [Daanoz/ha-google-photos#23]
**Is your feature request related to a problem? Please describe.**

I'd like to show a carousel of Google Photos in my Home Assistant dashboard on my camper van while I'm traveling with intermittent connectivity.

**Describe the solution you'd like**

I'd like to push a button to have the integration synchronize an offline copy of a particular Google Photos album.  Once that's done, all of the photos and their metadata would be retrieved from the local filesystem without hitting the network.

If the button is modeled as a home assistant entity, then I could also write an automation to periodically initiate a sync when the network is available under appropriate conditions.

Alternatively, the integration could download the photos directly into the home assistant Local Media directory.

**Comment by Daanoz** [comment]
It's something I've already looked into a bit, since at the moment, pictures get re-downloaded when they reappear as random selected media. However, it reads like this is something that would work against Google's [acceptable use policy](https://developers.google.com/photos/library/guides/acceptable-use#minimize-access). 

Not sure If [these solutions](https://www.multcloud.com/tutorials/sync-google-photos-to-pc-1207.html) would work for you, but if they do, I could look into creating a separate integration that could do the same functionality based on a folder that's accessible directly from HA.

**Comment by j9brown** [comment]
My solution was to download my photo wall album from Google Photos as a big zip file and drop it into the Home Assistant media folder.

I had some trouble with HVIC files not being supported by the screensaver so I wrote a script to convert the files to a supported format.  It works pretty well.
