### ISSUE TITLE
No image in app

### ISSUE THREAD

**Issue by realjax** [Daanoz/ha-google-photos#31]
I have this integration working fine on my desktop browser and even the HA app on my mac.

I get a nice display like so:
![Screenshot 2023-06-21 at 16 03 54](https://github.com/Daanoz/ha-google-photos/assets/883435/2ece254a-44a3-4ec2-8d37-c74be370c76d)

but in the android app the image never loads:
![Screenshot_2023-06-21-16-13-57-315_io homeassistant companion android](https://github.com/Daanoz/ha-google-photos/assets/883435/23c48f81-e798-41ec-80ba-44f7ee672f30)

Any idea why that is ?

**Comment by Daanoz** [comment]
Could you share some details of your setup? Local or remote? Http or Https?

I personally use https via Nabu Casa and locally, and it doesn't seem to cause issues when trying to display the photos. I did ran into some other people mentioning a similar issue:

https://github.com/home-assistant/android/issues/838
https://community.home-assistant.io/t/companion-app-doesnt-show-picture-entity/284135

The way the photos are served is actually handled by home assistant and not the integration, however I can't rule out the integration for 100% so it's interesting to know if this is caused by the issue mentioned above.

**Comment by realjax** [comment]
Yes, definitely something to do with ssl. When I try connecting my HA instance via my external address (not casa thingie but correctly configured with a valid certificate) over https the image also doesnt show in the browser.  Funnily enough the app never shows images, both htttp and https do not show3inages in the app

**Comment by realjax** [comment]
Sorry my fat fingers pushed a few buttons too many and I accidentally closed the issue

**Comment by realjax** [comment]
Last night my HA restarted and it has been working since. 
Note: I did restart after installing this integration as well, but maybe it need two of em :)  

For now this seems to work just fine, thanks for your help !

**Comment by realjax** [comment]
Actually it is hit or miss. More miss then hit. It did work for a bit like I mentioned but is now failing again.

**Comment by Daanoz** [comment]
So, haven't been able to look into it for a bit. This is actually pretty tricky to debug without a reproducible problem.

Couple of things to try:
- What happens if you open HA via the android browser? Same issue?
- Anything visible in the app logging? (settings -> Companion App -> Show and Share Logs)
