### ISSUE TITLE
Add support for rotating google photo as background when cast to google nest hub

### ISSUE THREAD

**Issue by evilrobotfromouterspace** [Daanoz/ha-google-photos#43]
**Is your feature request related to a problem? Please describe.**
I've successfully set up this google photos album integration to pull a random image and show it as a dashboard background using wallpanel. It works perfectly when viewing in a web browser, but when I cast it to a google nest hub using HA's built in casting functionality, the background image does not display on a nest hub. It appears that the google nest hub does not allow for the same type of link that the google photo album entity integration provides.

**Describe the solution you'd like**
Extend support for a rotating google photo to be used as a dashboard background image when casting to google nest hub

**Describe alternatives you've considered**
I've attempted to set a rotating google image as a background image in a dashboard view vs setting it as a wallpanel image. Neither solution works when casting to a google nest hub.

Here's the dashboard definition that works on a web browser but does not show a background image when cast to a nest hub.

`
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: false
  fade_in_time: 2
  crossfade_time: 2
  image_url: media-entity://camera.google_photos_foo_media
  image_order: random
  display_time: 300
  show_images: true
  image_background: image
  image_animation_ken_burns: true
  image_fit: contain
  cards:
    - type: custom:digital-clock
    - initial_view: listWeek
      type: calendar
      entities:
        - calendar.family
  card_interaction: true
views:
  - title: Home
    cards:
      - type: custom:digital-clock
      - initial_view: listWeek
        type: calendar
        entities:
          - calendar.family
      - type: picture-entity
        entity: camera.google_photos_foo_media

`

**Comment by ron-osu** [comment]
+1 for this - I cannot seem to get the Google Photos camera entity to display on the Nest Hub using any type of card, background image, or theme within a dashboard.  The only way it works is casting the camera entity directly from the Media section to the Nest Hub.  Everything works when viewing the same dashboard from Firefox or another browser, just not the Nest Hub.

**Comment by Daanoz** [comment]
I did some testing, and the issue seems to be with wallpanel: https://github.com/j-a-n/lovelace-wallpanel/issues/45. I did manage to create a workaround, but I need to find some time to clean it up and create a pull request in the wallpanel repo.

**Comment by ron-osu** [comment]
> I did some testing, and the issue seems to be with wallpanel: [j-a-n/lovelace-wallpanel#45](https://github.com/j-a-n/lovelace-wallpanel/issues/45). I did manage to create a workaround, but I need to find some time to clean it up and create a pull request in the wallpanel repo.

Do you have any details on what specifically is causing the issue?  I think it's an HA (dashboard) Cast incompatibility with both Google Photos and WallPanel on Nest Hub devices.

Based on my testing:
- I cannot get the Google Photos camera entity to work using any type of Lovelace card unless I use DashCast to cast the dashboard instead of native HA Cast.  This is even without WallPanel involved.
- I also cannot get WallPanel to work with native HA cast feature.  Just like Google Photos, it works fine when I use DashCast

For me anyway, the common issue seems to be that both Google Photos and WallPanel require DashCast (instead of the native HA Cast feature) in order to be functional on Google Nest Hub devices.  This is unfortunate because it seems most of the official recommendations are to use native HA cast for dashboards.

My testing is a few months and could be flawed, or perhaps things have changed.

Hope this helps.  Regardless, thanks for all your efforts!!
